# Generated by Django 6.0.2 on 2026-05-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0003_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField()),
                ('total_tables', models.PositiveIntegerField()),
                ('available_tables', models.PositiveIntegerField()),
            ],
        ),
    ]
