# Generated by Django 6.0.2 on 2026-05-15 12:42

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0004_cafetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafetable',
            name='available_tables',
        ),
        migrations.RemoveField(
            model_name='cafetable',
            name='table_name',
        ),
        migrations.RemoveField(
            model_name='cafetable',
            name='total_tables',
        ),
        migrations.AddField(
            model_name='cafetable',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cafetable',
            name='table_number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='tables',
            field=models.ManyToManyField(to='cafe_app.cafetable'),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Reserved', max_length=30),
        ),
    ]
