# Generated by Django 6.0.2 on 2026-05-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_app', '0010_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
